---
os: linux
dist: xenial

language: python
python:
  - "3.7.3"

env:
  - BOTO_CONFIG="/dev/null"

before_install:
  - wget -c "http://nlp.stanford.edu/software/stanford-corenlp-full-2018-10-05.zip"

install:
  - pip install -r requirements.txt
  - python -m nltk.downloader averaged_perceptron_tagger brown cmudict names punkt stopwords wordnet
  - python -m gensim.downloader --download glove-wiki-gigaword-50
  - unzip stanford-corenlp-full-2018-10-05.zip -d ..
  - cd ../stanford-corenlp-full-2018-10-05
  - nohup java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000 &
  - cd ../linguine-python

script:
  - travis_wait nosetests

services:
  - mongodb
