language: python
services: mongodb
python:
  - "3.4"
  - "3.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: "pip install -r requirements.txt"

before_script: python -m textblob.download_corpora

# command to run tests, e.g. python setup.py test
script:  PYTHON_ENV=test nosetests
