language: python

python:
  - "3.6"

env:
  - BOTO_CONFIG="/dev/null"

before_install:
  - wget -c "http://nlp.stanford.edu/software/stanford-corenlp-full-2015-12-09.zip"

install:
  - pip install -r requirements.txt
  - python -m nltk.downloader stopwords names cmudict brown punkt averaged_perceptron_tagger maxent_treebank_pos_tagger wordnet
  - git clone https://github.com/ritlinguine/stanford_corenlp_pywrapper ../stanford_corenlp_pywrapper
  - pip install ../stanford_corenlp_pywrapper
  - unzip -p stanford-corenlp-full-2015-12-09.zip stanford-corenlp-full-2015-12-09/stanford-corenlp-3.6.0-models.jar >../stanford_corenlp_pywrapper/stanford_corenlp_pywrapper/lib/stanford-corenlp-3.6.0-models.jar
  - rm stanford-corenlp-full-2015-12-09.zip
  - python -m gensim.downloader --download glove-wiki-gigaword-50

script:
  - travis_wait nosetests

services:
  - mongodb
