language: python

python:
  - "3.6"

env:
  - BOTO_CONFIG="/dev/null"

before_install:
  - wget -c "http://nlp.stanford.edu/software/stanford-corenlp-full-2018-10-05.zip"

install:
  - pip install -r requirements.txt
  - python -m nltk.downloader stopwords names cmudict brown punkt averaged_perceptron_tagger maxent_treebank_pos_tagger wordnet
  - unzip stanford-corenlp-full-2018-10-05.zip -d ..
  - python -m gensim.downloader --download glove-wiki-gigaword-50

script:
  - travis_wait nosetests

services:
  - mongodb
