language: python

matrix:
  include:
    - python: 3.4

before_install:
 - travis_retry wget https://bootstrap.pypa.io/get-pip.py
 - python get-pip.py
 - pip install -r requirements.txt
 - travis_wait 30 python -m nltk.downloader stopwords names cmudict brown punkt averaged_perceptron_tagger
 - git clone https://github.com/ritlinguine/stanford_corenlp_pywrapper scp_repo
 - ln -s scp_repo/stanford_corenlp_pywrapper .
 - wget -c "https://nlp.stanford.edu/data/glove.6B.zip" "https://raw.githubusercontent.com/RaRe-Technologies/gensim/develop/gensim/scripts/glove2word2vec.py"
 - unzip -p glove.6B.zip glove.6B.50d.txt >glove.6B.50d.txt
 - python3.4 glove2word2vec.py --input glove.6B.50d.txt --output glove.6B.50d.w2vformat.txt
 - rm glove.6B.zip glove.6B.50d.txt glove2word2vec.py
 - mv glove.6B.50d.w2vformat.txt linguine/ops/

script:
 - travis_wait nosetests

services:
 - mongodb
