language: python

matrix:
  include:
    - python: 3.4

before_install:
 - travis_retry wget https://bootstrap.pypa.io/get-pip.py
 - python get-pip.py
 - pip install -r requirements.txt
 - travis_wait 30 python -m nltk.downloader stopwords names cmudict brown punkt averaged_perceptron_tagger
 - git clone https://github.com/ritlinguine/stanford_corenlp_pywrapper scp_repo
 - ln -s scp_repo/stanford_corenlp_pywrapper .

script:
 - travis_wait nosetests

services:
 - mongodb
