language: python

matrix:
  include:
    - python: 3.4
      env: "NUMPY=1.8 SCIPY=0.13"

before_install:
 - travis_retry wget https://bootstrap.pypa.io/get-pip.py
 - python get-pip.py
 - pip install nltk
 - pip install numpy==1.8
 - pip install scipy==0.13
 - pip install matplotlib
 - pip install nose
 - travis_wait 30 python -m nltk.downloader stopwords
 - pip install -r requirements.txt
 - git clone https://github.com/Pastafarians/stanford_corenlp_pywrapper scp_repo
 - ln -s scp_repo/stanford_corenlp_pywrapper .

#before_install:
# - travis_retry wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh
# - chmod +x miniconda.sh
# - bash miniconda.sh -b -p $HOME/miniconda
# - export PATH=/home/travis/miniconda/bin:$PATH
# - travis_wait conda update --yes conda
# - conda install --yes numpy=$NUMPY scipy=$SCIPY matplotlib pip
# - conda info -a
# - pip install -r requirements.txt
# - git clone https://github.com/brendano/stanford_corenlp_pywrapper scp_repo
# - ln -s scp_repo/stanford_corenlp_pywrapper .

script:
 - travis_wait nosetests

services:
 - mongodb
