language: python

matrix:
  include:
    - python: 3.4
      env: "NUMPY=1.8 SCIPY=0.13 'SPLAT-LIBRARY=0.2.3'"

before_install:
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda
 - conda install --yes numpy=$NUMPY scipy=$SCIPY splat=${SPLAT-LIBRARY} matplotlib pip
 - pip install -r requirements.txt
 - git clone https://github.com/brendano/stanford_corenlp_pywrapper scp_repo
 - ln -s scp_repo/stanford_corenlp_pywrapper .

script:
 - nosetests

services:
 - mongodb
